### ISSUE TITLE
Cannot mkdir db.git: Permission denied

### ISSUE THREAD

**Issue by NicolaDes** [turingarena/turingarena#47]
I tried to launch the `turingarena skeleton` command and gave exit status error 128. Below the full error:
```
Sending work dir: /home/sphero/code/turingarenaExamples (current dir: sat_to_3sat/callbacks)...
fatal: cannot mkdir db.git: Permission denied
Traceback (most recent call last):
  File "/usr/local/bin/turingarena", line 11, in <module>
    sys.exit(turingarena_cli())
  File "/usr/local/lib/python3.5/dist-packages/turingarena_cli.py", line 95, in turingarena_cli
    "git init --bare --quiet db.git",
  File "/usr/lib/python3.5/subprocess.py", line 581, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['ssh', '-o', 'BatchMode=yes', '-o', 'LogLevel=error', '-o', 'UserKnownHostsFile=/dev/null', '-o', 'StrictHostKeyChecking=no', '-p', '20122', 'turingarena@localhost', 'git init --bare --quiet db.git']' returned non-zero exit status 128
```
This error appears also when i evaluate a submission with `turingarena evaluate [path/to/sub]` command.

I'm using `python 3.5.2v` and `turingarena/turingarena:latest` docker image.

**Comment by alerighi** [comment]
Hi, 
there is a permission issue, I discovered it yesterday when working on the new cli implementation, practically /run/turingarena is mounted in the docker container with the wrong permissions. 

I fixed it yesterday in the develop branch, so make sure to be in the develop (`git checkout develop`) and do a `git pull`. It should fix the issue. 

Let me know if this fixed it, so I can close the issue.
