### ISSUE TITLE
Implement error reporting for cloud submissions

### ISSUE THREAD

**Issue by cairomassimo** [turingarena/turingarena#73]
The error, if any, is printed to `stdout` by HyperSH.
This output should be read by AWS Lambda, by invoking HyperSH, either with an automatic exponential backoff, or on API calls, and it should saved to DynamoDB. The evaluation should be marked as failed unless the content of `stdout` is empty (or unless it contains a specific magic string).

This is an example of error dumped to `stdout` by HyperSH, occurring if the provided repository does not exist:

```
Traceback (most recent call last):
  File "/usr/local/turingarena/src/turingarena_impl/api/hypersh_api.py", line 29, in main
    execute_request()
  File "/usr/local/turingarena/src/turingarena_impl/api/hypersh_api.py", line 18, in execute_request
    handle(request)
  File "/usr/local/turingarena/src/turingarena_impl/api/hypersh_api.py", line 13, in handle
    return handler(request)
  File "/usr/local/turingarena/src/turingarena_impl/api/hypersh_evaluate.py", line 5, in handle_evaluate
    store_events(request.evaluation_id, evaluate(request.evaluate_request))
  File "/usr/local/turingarena/src/turingarena_impl/api/dynamodb_events.py", line 34, in store_events
    for i, e in enumerate(events):
  File "/usr/local/turingarena/src/turingarena_impl/evaluation/evaluate.py", line 21, in evaluate
    with create_working_directory(evaluate_request.working_directory, local_execution=local_execution) as work_dir:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/usr/local/turingarena/src/turingarena_impl/cli_server/pack.py", line 32, in create_working_directory
    git.fetch_repository(working_directory.pack.repository)
  File "/usr/local/turingarena/src/turingarena_impl/cli_server/git_manager.py", line 61, in fetch_repository
    subprocess.run(cmd, env=self._base_env, check=True)
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['git', 'fetch', '--recurse-submodules=yes', '--quiet', 'https://github.com/turirngarena/turingarena']' returned non-zero exit status 128.
```

**Comment by cairomassimo** [comment]
We may rather output a JSON or pickle to `stdout`, containing either a payload marking the success of the evaluation, or the exception message and traceback on errors.
